name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4 # also caches the tools
      - uses: Swatinem/rust-cache@v2 # caches ~/.cargo and target/
      - run: mise run ci
